### ISSUE TITLE
Clique module for pfUI UnitFrames

### ISSUE THREAD

**Issue by shagu** [kxseven/Clique#1]
Hi,

I made a simple Clique-Plugin to support pfUI-Unitframes without any need to modify pfUI's code.
Just thought you might be interested in this:
https://github.com/shagu/Clique/commit/a5ee56c3f803afbdda07bae9cd330e0d4a75d75a

**Comment by ghost** [comment]
Currently this does not work yet with this version of Clique and pfUI 1.6.

Just an FYI.

**Comment by shagu** [comment]
The Clique I linked here is the original one plus a pfUI-integration plugin. It works fine with pfUI.
But it's no Problem, if you want to stick to your solution. I just thought a proper plugin would be appreciated. 
Nvm though...
